export const retryableNames = new Set([
    "APIConnectionError",
    "APIConnectionTimeoutError",
    "ModelEmptyResponseError",
    "ResponsesWebsocketError",
    "TimeoutError",
  ]),
  retryableApiCodes = new Set([
    "bad_response_status_code",
    "basispoints_upstream_error",
    "server_error",
    "server_is_overloaded",
  ]),
  retryableApiErrorTypes = new Set(["service_unavailable_error"]),
  retryableHttpStatuses = new Set([520]),
  retryableMessages = new Set(["Received empty response from chat model call."]),
  nonRetryableApiErrorTypes = new Set(["usage_limit_reached"]),
  retryableCodes = new Set([
    "ECONNABORTED",
    "ECONNREFUSED",
    "ECONNRESET",
    "EHOSTUNREACH",
    "ENETDOWN",
    "ENETRESET",
    "ENETUNREACH",
    "ENOTFOUND",
    "ETIMEDOUT",
    "UND_ERR_CONNECT_TIMEOUT",
    "UND_ERR_HEADERS_TIMEOUT",
    "UND_ERR_SOCKET",
    "UNKNOWN_CERTIFICATE_VERIFICATION_ERROR",
    "stream_read_error",
  ]);
export const retryableHandshakeStatuses = new Set([408, 429]),
  nonRetryableWebsocketCloseCodes = new Set([1002, 1003, 1007, 1008, 1009, 1010]),
  structuredErrorNames = new Set(["ResponsesWebsocketError"]),
  uninformativeCauseNames = new Set(["Error", "TypeError"]);
