/* oxlint-disable @pandacss/no-descendant-selectors -- Markdown elements are generated by the renderer. */
/* oxlint-disable @pandacss/no-margin-properties -- Markdown typography requires element-specific spacing. */
import { css } from "styled-system/css";

export const rendered = css({
  "& .task-list-item": { listStyleType: "none" },
  "& .task-list-item > input": { marginInlineEnd: "2", verticalAlign: "middle" },
  "& > :first-child": { marginBlockStart: "zero" },
  "& > :last-child": { marginBlockEnd: "zero" },
  "& a": {
    _hover: { color: "text" },
    color: "syntaxMeta",
    textDecoration: "underline",
    textUnderlineOffset: "0.15em",
  },
  "& blockquote": {
    borderInlineStartWidth: "medium",
    borderLeftColor: "lineStrong",
    color: "mutedStrong",
    marginBlockEnd: "3",
    paddingInlineStart: "3",
  },
  "& blockquote > :last-child": { marginBlockEnd: "zero" },
  "& code": { wordBreak: "break-word" },
  "& h1": { fontSize: "xl" },
  "& h1, & h2, & h3, & h4, & h5, & h6": {
    marginBlockEnd: "3",
    marginBlockStart: "5",
    textStyle: "markdownHeading",
  },
  "& h2": { fontSize: "lg" },
  "& h3": { fontSize: "md" },
  "& h4, & h5, & h6": { fontSize: "sm" },
  "& hr": { borderBlockStartWidth: "hairline", borderColor: "lineStrong", marginBlock: "4" },
  "& img": {
    borderColor: "line",
    borderWidth: "hairline",
    display: "block",
    height: "auto",
    marginBlockEnd: "3",
    maxWidth: "full",
  },
  "& li > ol, & li > ul": { marginBlockEnd: "zero", marginBlockStart: "1" },
  "& li::marker": { color: "mutedStrong" },
  "& ol": { listStyleType: "decimal", marginBlockEnd: "3", paddingInlineStart: "5" },
  "& p": { marginBlockEnd: "3" },
  "& pre": { marginBlockEnd: "3" },
  "& table": { borderCollapse: "collapse", minWidth: "tableContent", width: "full" },
  "& th": { background: "surfaceInset", fontWeight: "bold", textAlign: "left" },
  "& th, & td": {
    borderColor: "line",
    borderWidth: "hairline",
    padding: "2",
    verticalAlign: "top",
  },
  "& ul": { listStyleType: "disc", marginBlockEnd: "3", paddingInlineStart: "5" },
  "& ul.contains-task-list": { listStyleType: "none", paddingInlineStart: "zero" },
  '&[data-source-visible="true"]': { visibility: "hidden" },
  lineHeight: "markdown",
  maxWidth: "full",
  minWidth: "zero",
  width: "full",
});
export const tableScroll = css({
  marginBlockEnd: "3",
  maxWidth: "full",
  overflowX: "auto",
  overscrollBehaviorX: "contain",
  width: "full",
});
export const region = css({
  lineHeight: "markdown",
  maxWidth: "full",
  minWidth: "zero",
  position: "relative",
  width: "full",
});
export const source = css({
  "& code": {
    font: "inherit",
    overflowWrap: "anywhere",
    whiteSpace: "inherit",
  },
  background: "clear",
  borderWidth: "zero",
  maxWidth: "full",
  minWidth: "zero",
  overflow: "visible",
  padding: "zero",
  textStyle: "sourceCode",
  whiteSpace: "pre-wrap",
  wordBreak: "break-word",
});
export const inlineCode = css({
  display: "inline",
  paddingBlock: "0.5",
  paddingInline: "1.5",
  textStyle: "inlineCode",
  verticalAlign: "baseline",
});
