// OpenAI Codex main identifier and request headers.
export const codexProtocol = {
  cookieHostSuffixes: [".chatgpt.com", ".chatgpt-staging.com"],
  cookieHosts: ["chatgpt.com", "chat.openai.com", "chatgpt-staging.com"],
  cookieNamePrefix: "cf_chl_",
  cookieNames: [
    "__cf_bm",
    "__cflb",
    "__cfruid",
    "__cfseq",
    "__cfwaitingroom",
    "__oailb",
    "_cfuvid",
    "cf_clearance",
    "cf_ob_info",
    "cf_use_ob",
  ],
  maxRedirects: 10,
  npmLatestUrl: "https://registry.npmjs.org/@openai%2fcodex/latest",
  originator: "codex_cli_rs",
  requestHeaders: [
    "authorization",
    "chatgpt-account-id",
    "cookie",
    "content-encoding",
    "openai-organization",
    "openai-project",
    "session-id",
    "thread-id",
    "x-codex-beta-features",
    "x-codex-installation-id",
    "x-codex-parent-thread-id",
    "x-codex-routing-hint",
    "x-codex-turn-metadata",
    "x-codex-turn-state",
    "x-codex-window-id",
    "x-openai-internal-codex-responses-lite",
    "x-openai-memgen-request",
    "x-openai-subagent",
    "x-responsesapi-include-timing-metrics",
    "x-client-request-id",
  ],
  websocketBeta: "responses_websockets=2026-02-06",
} as const;
